spring.application.name=Car-Dealership-Inventory-System


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cardealership2
spring.datasource.username=hetgajera
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port =8082